## Numpy Exercise - Daniella Salima

In [1]:
import numpy as np

## Execution

In [2]:
data = np.array([1,2,3,4,5])
print(data)
print(len(data))
print(type(data))
print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


## Exercises lecture slide

### Import 2D  array

In [3]:
arrD = np.array([[25, 50, 75, 100], [20, 40, 60, 80]])


In [4]:
print(arrD)

[[ 25  50  75 100]
 [ 20  40  60  80]]


### Array Indexing

In [5]:
print(arrD[0])

[ 25  50  75 100]


### Array slicing

In [6]:
print(arrD[0:2])

[[ 25  50  75 100]
 [ 20  40  60  80]]


### Array Sorting

In [7]:
print(np.sort(arrD))

[[ 25  50  75 100]
 [ 20  40  60  80]]


In [8]:
arrA = np.array(['samsung', 'apple', 'infinix', 'techno', 'xiaomi'])

In [9]:
print(np.sort(arrA))

['apple' 'infinix' 'samsung' 'techno' 'xiaomi']
